### ISSUE TITLE
Test failed

### ISSUE THREAD

**Issue by Clement-Chalencon** [suzanje/module-test-puppeteer#6]
## Description : 
When command "npm test -- --runInBand"" is launch the test "tests/shorten-anonymous.test.js" failed   
![image](https://user-images.githubusercontent.com/58743343/111649577-c87fd680-8804-11eb-9019-ebfdd797577d.png)  
## How to reproduce  
1 - Go to the project root
2 - In a console launch npm test -- --runInBand
  
## Proposed solution
None

## Linked Issues
None  

## Context
This project seems to be an old non maintained project and this issue is just a fake one

**Comment by UlysC** [comment]
Please refer to the guidelines as to writing a proper issue thank you
