### ISSUE TITLE
Protocol error (Target.createTarget): Target closed.

### ISSUE THREAD

**Issue by AbdelkaderA** [suzanje/module-test-puppeteer#7]
**Procedure**

-Clone du repo GitHub
-npm install depuis WSL
-npm test -- --runInBand depuis WSL
Cela n'a pas fonctionné car il me manque la dépendance (libxss1) a ajouter dans la doc.
-npm test -- --runInBand depuis WSL
Et ensuite les erreurs sont apparu

# Erreur de connexion

      41 |     beforeAll(async () => {
      42 |         // ouvrir un onglet dans le navigateur
    > 43 |         page = await global.__BROWSER__.newPage()
         |                                         ^
      44 |     }, timeout)
      45 | 
      46 | });

**Configuration**
-Windows 10 Version 10.0.19041 Build 19041
-Processeur Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz, 2112 MHz, 4 cœur(s), 8 
  processeur(s) logique(s)
-Mémoire physique (RAM) installée	16,0 Go
-Testé VS Code 1.54.1

**Comment by UlysC** [comment]
Abdelkader Atamaa ? C'est vraiment vous ? Je peux avoir un autographe ?
